### ISSUE TITLE
Doesn't work in Incognito mode

### ISSUE THREAD

**Issue by 14422** [rain-fighters/AudioPick#13]
Test with latest Chrome version: 65.0.3325.181 and the plugin is also set to be enabled in incognito mode.

Changing audio outputs doesn't actually change it.

Another smaller issue in normal browser mode: Default output device is not used on Netflix for some reason, but is on Twitch. With Netflix I have to select some other output and then back to the one that I actually want.

**Comment by necropola** [comment]
Fixing Netflix is already on my list.
Need to check why it does not work in incognito mode or rather why it can't work in incognito mode.
