### ISSUE TITLE
Please Suppress Console output!

### ISSUE THREAD

**Issue by jjspace** [rain-fighters/AudioPick#14]
Can you please add a setting to suppress console output or remove it entirely?

I'm a web developer myself and I find it very annoying when I open DevTools on a page and see a ton of messages from AudioPicker. I totally understand if they were added as a form of debugging (which is why you could add a setting) but they are not useful in general and just cause clutter.

**Comment by necropola** [comment]
Will have a look. Probably make enabling/disabling diagnostic output an option.

**Comment by jjspace** [comment]
I spent some time looking into this myself and I came up with 2 solutions. Either you can change the `log()` function in `content.js` to check for a debug setting to be true. Or you can convert that same function to log to the background like all the other js files. I'm not sure what your initial intent was so maybe this was just overlooked and was actually the intended behavior? 

Regardless, thanks for looking into it!

**Comment by Ancyker** [comment]
+1

As a developer, this is really annoying because it clutters up my console logs.

**Comment by gopa2000** [comment]
+1

Web developer here as well, I realise that this issue is a bit old but I'd appreciate it if the console output could be suppressed.
