### ISSUE TITLE
Support for selecting 2 audio output devices?

### ISSUE THREAD

**Issue by lazyway** [rain-fighters/AudioPick#18]
I like to send the audio to VirtualAudioCable (muxed with my own mic for chat) and hear the sound through my headset. Is there a way to configure your app to do this?

**Comment by necropola** [comment]
Afaik there is no way to assign more than one sink to an audio/video
element.
What you should be able to do is mix the audio input for the chat
application (discord/skype) using voicemeeter.

I'm using B2 as audio input for Discord/Skype which allows me to mix and
preview microphone and other audio sources as needed.


https://plus.google.com/108590874920717613332/posts/13DJeyBQVDj
