### ISSUE TITLE
Causes Large Lag Spikes on Certain Sites

### ISSUE THREAD

**Issue by starkline** [rain-fighters/AudioPick#28]
Fantastic extension! As an audio engineer, it's great to be able to choose an output device in windows. Thanks!

I've found a very intermittent issue. On certain sites the extension causes large lag. The one site that I can reproduce the issue is Chess.com.

On Chess.com, if you find your way to the "[Solve Puzzles](https://www.chess.com/puzzles)" section, the issue should be evident. 

Unfortunately, if you don't have a chess.com subscription, you won't be able to play more than a few puzzles. I wish I could provide another example, but it's the only one I've found where I can reliably reproduce the issue.

Rain-Fighters, if you come back to the extension, I hope you can find the time to investigate.

Thanks!

**Comment by theY4Kman** [comment]
FWIW, I can reproduce this lag spike while browsing Netflix and hovering over titles to play their sample videos. After a handful of attempts, the delay between hovering and expanding, as well as to video playback, grows enormous. A single CPU hangs at full load.

The DevTools console looks like this:
![image](https://user-images.githubusercontent.com/33840/67645001-7a5ef000-f8fc-11e9-8c60-ba3016bfc09c.png)

**Comment by starkline** [comment]
Lol. So, that's what it was. I was experiencing the same thing with Netflix, but I never took the time to investigate the cause.

**Comment by necropola** [comment]
That's interesting and I'm able to reproduce it.
Not sure yet, why it happens, but I'll take a look.
