### ISSUE TITLE
It's not working when VB Audio Default on Chrome

### ISSUE THREAD

**Issue by ozzymanborn** [rain-fighters/AudioPick#33]
It's only playing with default device and not allow change in chrome.

But I am able to work with yandex browser, edge and vivaldi browser.

**Comment by OPsouL974** [comment]
Same problem ... I know what is happening.. it is changing the audio source in the windows OS, when I set the windows sound options to the VB channel I'm using AudioPick get to, I get sound.  I'd say the worst part is it worked fine before Q3 2019... if I can have that version that would be nice.
