### ISSUE TITLE
Might want to try.. not an issue.

### ISSUE THREAD

**Issue by StrictlyVox** [rain-fighters/AudioPick#38]
I installed this and it worked, also it can't randomly happened it work out of nowhere... I'm not sure, I'm just listing this out here, someone might have a chance to find a fix for it :D
Download: <a href="https://chrome.google.com/webstore/detail/audiozapper-what-you-see/dbcdnhfnlpncjompeodddgcbcnloadij"> AudioZapper</a>
`Not Advertising`

**Comment by Alt-Avatar** [comment]
The program AudioZapper has nothing to do with AudioPick.  They do not do the same things.

**Comment by StrictlyVox** [comment]
then how does audiopick worked without me installing it. lol

**Comment by Alt-Avatar** [comment]
With AudioPick, you can control which audio device you want sound directed to per Chrome tab.  Example: I have Youtube opened on one tab, and let's say some music website on a different tab.  I send my Youtube audio to my headset and send the music tab sight to my speakers that are connected to my computer.  This is done per each tab, not for the Chrome application itself.  What AudioZapper does is control the volume per application.  Most people who use AudioPick are trying to control audio per tab.

AudioZapper does what Window's 10 provides automatically through the sound settings within Windows 10.  You can control application output using Windows 10 settings but you can't direct audio per tab in Chrome using Windows 10 settings.  You can only control the output per Google Chrome application.
