### ISSUE TITLE
Remember preferred Audio Device per site (optional)

### ISSUE THREAD

**Issue by necropola** [rain-fighters/AudioPick#4]
### From WebStore Feedback
Would be cool if you could be able to add websites with default audio devices. For example I almost always listen to music on YouTube via Speakers. Same time I can watch some streams on my connected TV via HDMI Audio.

**Comment by necropola** [comment]
That's an interesting idea and the remember choice part isn't hard to implement. Would a remember my choices checkbox on the Options page of the Extension meet the requirements?

**Comment by alphanimal** [comment]
I would love this feature too!

**Comment by TheRedDev** [comment]
would just like to 'upvote' this issue, i run youtube/twitch/hangouts in 'app' mode and cant switch them in that mode, but if there was a memory they'd work great :)

**Comment by xeon927** [comment]
+1 - would also love this feature. I have some weird overkill setup at home involving a digital mixer and separate faders for different applications, so being able to put media sites (eg, Netflix, YouTube, Plex, etc) on one fader, and have it remember would be fantastic!

**Comment by alphanimal** [comment]
@xeon927 Just curious what mixer do you have? I do the same with the Soundcraft Signature 12MTK. Love the physical faders to control volume.

**Comment by TheRedDev** [comment]
I use Voicemeter Banana

**Comment by xeon927** [comment]
> @xeon927 Just curious what mixer do you have? I do the same with the Soundcraft Signature 12MTK. Love the physical faders to control volume.

Running a Soundcraft Si Impact :)

**Comment by alphanimal** [comment]
Nice! That's an expensive sound card though :)

**Comment by cogat** [comment]
+1. I use [https://staticz.com/](Sound Control) to do this at app level. I would love it if most sites played through the default output, but Plex/Youtube/Vimeo played through the big speakers.

**Comment by cogat** [comment]
Thinking about implementation, I think once you choose a device for a tab, show a checkbox saying "Use this device every time I visit <sitename.com>".

**Comment by disco0** [comment]
> choose a device for a tab, show a checkbox saying "Use this device every time I visit <sitename.com>".

A simple toggle like this that appends the new configuration value to the bottom of a stored list (new line separated, (quoted) site pattern / output device pairs, read top to bottom) would be great—also a little overkill, though, so maybe something that's partially the way to that.
