### ISSUE TITLE
Not working with Nahimic

### ISSUE THREAD

**Issue by p3yn** [rain-fighters/AudioPick#41]
Plugin not working with Nahimic intalled, Wont let me choose any output

**Comment by ret394** [comment]
Search for Nahimic audio issues. Google, Bing, whatever you use.

The urls are -
google.com  bing.com duckduckgo.com

Specific examples - 
https://nahimic.helprace.com/i734-new-nahimic-3-audio-driver-update

Compare to their page for contrast -
https://www.msi.com/page/nahimic

thanks.
you're welcome, as always. all the best. 👍
don't say '... passim' to folks on Github or other social media sites.

[ret394](https://github.com/ret394)
