### ISSUE TITLE
audio pick does not work on chrome (win10)

### ISSUE THREAD

**Issue by dmitrychepel** [rain-fighters/AudioPick#43]
Tested with latest version of chrome (84.0.4147.135) with youtube and twitch, windows 10 2004
Selecting any output device has no effect, only plays through default device.

**Comment by Zhyrclew** [comment]
Check this out maybe? https://github.com/rain-fighters/AudioPick/issues/36#issuecomment-632015099

**Comment by dmitrychepel** [comment]
it is helped me.

**Comment by hdrut** [comment]
Yes it does, you have to allow microphone permission.
