### ISSUE TITLE
Audio changing back to default device 

### ISSUE THREAD

**Issue by kieranlee999** [rain-fighters/AudioPick#45]
When watching Disney, netflix etc when the next episode comes on the audio source automatically changes back to the system default rather than what is selected in the tab and what was selected before the episode changed.

**Comment by 53RP** [comment]
Im having this issue too, ive changed all my audio device's settings , as ive heard this could be an issue.. still persists

![Image](https://github.com/user-attachments/assets/4abf1ca7-774b-4c53-980f-38bcabb89527)

**Comment by necropola** [comment]
You've reopened a rather old issue for a very different (outdated) version of the extension. 

- Are you using the current version of the externsio, i. e. 0.3.10?
- The issue with certain devices being "locked" by exclusive access refers to AudioPick not being able to change the AudioSink at all.  So it's probably not related to your issue.
