### ISSUE TITLE
Chrome Store

### ISSUE THREAD

**Issue by waseeen** [rain-fighters/AudioPick#48]
Why not update the extension in the Chrome Web Store right now? I am really excited about the new version and I'm already using it, but some browsers (if not all) restrict the use of extensions that were not installed from the official store (usually disable them every time you restart the browser)

**Comment by necropola** [comment]
There is still a bit of fine-tuning and testing needed. Especially regarding microphone permissions, which I would really like to minimize. And then I need to "explain to google", (again) why the extension needs those permissions, etc. and possibly wait for them to review it.

So, please be patient. As you can see, light is at the end of the tunnel. :-)

**Comment by necropola** [comment]
Keep an eye on #47, when you interested in the current progress. My focus is currently
- on making the popup nicer and more informative
- and on minimizing the number of microphone excpetions added by the extension.

Closing this one ...
