### ISSUE TITLE
AudioPick randomly changes my default device

### ISSUE THREAD

**Issue by necropola** [rain-fighters/AudioPick#5]
original comment from @eddielucitt:

Hi, not a complicated issue, but definitely an annoying one! Hoping to help solve this in any way I can! 

My copy of AudioPick changes my default device about once a day, and I have to manually go into the settings and re-select my default device (a virtual cable output) every time this happens.

**Comment by necropola** [comment]
- Does it change the global (AudioPick  Options) device or the device chosen for a specific tab? 
- Does it change while Chrome is running?
- Does it always switch to the same device?

I may have spotted a problem in the code that reads the value from chrome storage.

**Comment by necropola** [comment]
original comment from @eddielucitt:

- Yes, it changes it in the default options.
- I'm not sure, I don't think so. I think it happens when I restart Chrome.
- No, it's a seemingly random device. Sometimes it defaults to NOTHING selected.

**Comment by eddielucitt** [comment]
Wanted to bump this, since I'm still having these issues. 

It appears the setting is reset every time I connect/disconnect a new audio device. I use a Bluetooth wireless headset so my available/default devices is always switching back and forth. 

Thanks again for this utility! First of it's kind!

**Comment by StingrayNine** [comment]
Hi, I wanted to chime in and say that this is still happening.
It might change when chrome restarts/updates but I forget to double-check.
I switches while chrome is running and not always to the same device.
I generally only notice this when looking at my mixer as I want chrome on one output and system on another. 

Please take a closer look into what might cause the setting on this incredibly useful add-on to change.
Thanks in advance!

**Comment by necropola** [comment]
Indeed there is an issue when adding/removing audio devices while chrome is running. Windows Plug&Play really doesn't play nicely ... (you may have noticed similar issues with game sound when changing audio devices while the game is running).
 
I'm probably able to catch this case. But I might need to switch from storing internal sink ids to storing device names and maintain a device name to sink id mapping table.

Thanks for your feedback.
