### ISSUE TITLE
Audio Output Devices Not Listed On Vivaldi

### ISSUE THREAD

**Issue by KitsuneNoMeiji** [rain-fighters/AudioPick#59]
Title says it all. When using the Vivaldi browser, output devices aren't even listed.

![vivaldi_0qBcMPYCo0](https://github.com/rain-fighters/AudioPick/assets/5057274/bf95d3cf-415e-4d5a-9fd0-6099b4808e67)

**Comment by KitsuneNoMeiji** [comment]
Can confirm, it's because I am using Vivaldi instead of Chrome. How unfortunate.

**Comment by necropola** [comment]
Vivaldi is not Chrome, Those APIs aren't identical. There is a reason why this extension is not available for Firefox which is - opposed to Vivaldo - a browser I'm actuallyusing myself ... closing.

**Comment by drugzncrime** [comment]
AAAAAAAAcktually... Vivaldi is built using the Chromium web browser project... so yeah. Here's what I have for ya - I'm on Pop!_Os and can confirm that it is not an OS issue as I had this extension on windows 11. But there is indeed an underlying issue somewhere in between the two. Vivaldi Shares the Chrome Store so its clear as to why someone would ask about the issue and hope to not get the thread closed with no explanation other than you just don't want to deal with it. In fact, it'd be less rude to say so. At least we would have some 'closure'.
