### ISSUE TITLE
Left align audio device names

### ISSUE THREAD

**Issue by alphanimal** [rain-fighters/AudioPick#6]
Hello!

I think it would make it easier to read if the playback channel names were left aligned and in alphabetical order. Also maybe an option do hide the hardware name?

![image](https://user-images.githubusercontent.com/29342016/31415220-4ab482ec-ae22-11e7-951b-497e6836a114.png)

@necropola You plugin is very helpful for me! Thanks a lot!

**Comment by necropola** [comment]
I'm considering your suggestion for the next version which will handle Device Names / Ids sdifferently anyway. Thanks for your feedback.
