### ISSUE TITLE
Audio output sources are not showing up on vivaldi.

### ISSUE THREAD

**Issue by drugzncrime** [rain-fighters/AudioPick#63]
Vivaldi is built using the Chromium web browser project so i'd like to try figure this out... I'm on Pop!_Os and can confirm that it is not an OS issue as I had this extension on windows 11 and forgot to mention in the other comment that when installed Chrome on this machine that there was in fact no issue. The extension works as intended. The problem is - Vivaldi is a much better browser built on the the same framework but for whatever reason - it no worky worky. There is indeed an underlying issue somewhere in between the two. I hope this issue can be reviewed without being swept under the rug.

**Comment by necropola** [comment]
See #12 and feel free to fix/adjust the extension yourself or rather contribute a patch. It's **Open Source** afterall.
