### ISSUE TITLE
VoiceMeeter incompatibility

### ISSUE THREAD

**Issue by explosive-diarrhea** [rain-fighters/AudioPick#9]
I'm having trouble redirecting audio from Chrome to the aux input VoiceMeeter, it just does not work. My desktop default output is VoiceMeeter Main INPUT, and i can easily direct some apps (TeamSpeak or Discord) to the AUX INPUT and manipulate the audio to my headset or speakers, but Chrome insists in remain on the Main INPUT  and can not be isolated. pls help!

**Comment by disco0** [comment]
Been using AudioPick to route to Voicemeeter (additonally through Virtual Audio Cable channel in it) for around six months, works flawlessly except for sites with [this know issue](https://github.com/rain-fighters/AudioPick/issues/2). I'm on Win7, not sure what OS you're on but seems like its something else in the chain besides AudioPick perhaps

**Comment by necropola** [comment]
This actually does not look like an incompatibility but exactly the scenario AudioPick was made for. I'm using VoiceMeeter myself on Windows 8.1
